"""Export harvested keys straight into an OmniRoute gateway.

Turns out/keys.txt into ready-to-run shell commands for the OmniRoute CLI:

    omniroute providers add <provider> --credential-stdin

(feed each key through stdin). Providers whose key isn't OpenAI-compatible are
still listed — the add command lets you point api_base/engine separately.

Modes:
    python tools/export_omniroute.py            # print commands (default, sh)
    python tools/export_omniroute.py --format sh|list|env
    python tools/export_omniroute.py --file PATH
"""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from farmer import keyfile

BANNER = "# Generated by auto-free-ai-api-farming tools/export_omniroute.py — review before running."


def sh_lines(rows: list[dict]) -> list[str]:
    lines = [BANNER, "# add each key: provider name must match an OmniRoute engine/provider",
             "# usage sample (per row):", "#   printf %s '<KEY>' | omniroute providers add <PROVIDER> --credential-stdin", ""]
    for r in rows:
        prov = r["provider"].lower().replace(" ", "")
        lines.append(f"# {r['provider']}  (account={r['account'] or '?'} {r['at']})")
        lines.append(f"printf '%s' '{r['key']}' | omniroute providers add {prov} --credential-stdin")
    return lines


def list_lines(rows: list[dict]) -> list[str]:
    return [f"{r['provider']}\t{r['key']}\t{r['account']}" for r in rows]


def env_lines(rows: list[dict]) -> list[str]:
    seen: dict[str, int] = {}
    lines = []
    for r in rows:
        base = r["provider"].upper().replace(" ", "_")
        seen[base] = seen.get(base, 0) + 1
        name = base if seen[base] == 1 else f"{base}_{seen[base]}"
        lines.append(f"{name}={r['key']}")
    return lines


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    fmt = "sh"
    path = keyfile.KEYFILE
    rest = list(args)
    if "--format" in rest:
        i = rest.index("--format"); fmt = rest[i + 1]; del rest[i:i + 2]
    if "--file" in rest:
        i = rest.index("--file"); path = Path(rest[i + 1]); del rest[i:i + 2]
    rows = keyfile.read_keys() if path == keyfile.KEYFILE else _read_any(path)
    if not rows:
        print("# no keys found (out/keys.txt empty?)")
        return 1
    table = {"sh": sh_lines, "list": list_lines, "env": env_lines}.get(fmt, sh_lines)
    print("\n".join(table(rows)))
    return 0


def _read_any(path: Path) -> list[dict]:
    rows = []
    for ln in path.read_text(encoding="utf-8").splitlines():
        if not ln.strip() or ln.startswith("#"):
            continue
        p = ln.split("\t")
        rows.append({"provider": p[0].strip(), "key": p[1].strip(),
                     "account": p[2][len("account="):] if len(p) > 2 and p[2].startswith("account=") else "",
                     "at": ""})
    return rows


if __name__ == "__main__":
    raise SystemExit(main())